// skills/ddd-angular/assets/context-template/__context__/presentation/views/__entity-kebab__-form/__entity-kebab__-form.ts
import {Component, inject} from '@angular/core';
import {FormBuilder, FormControl, ReactiveFormsModule, Validators} from '@angular/forms';
import {ActivatedRoute, Router} from '@angular/router';
import {BaseForm} from '../../../../shared/presentation/components/base-form/base-form';
import {__Entity__} from '../../../domain/model/__entity-kebab__.entity';
import {__Context__Store} from '../../../application/__context__.store';

/**
 * Routed view that creates or edits one __entity__.
 *
 * @remarks
 * One view serves both routes — the presence of an `id` parameter decides which.
 * The form collects and validates input as UX, then builds a {@link __Entity__}
 * and hands it to the store; the backend validates again and stays the authority.
 */
@Component({
  selector: 'app-__entity-kebab__-form',
  imports: [ReactiveFormsModule],
  templateUrl: './__entity-kebab__-form.html',
  styleUrl: './__entity-kebab__-form.css'
})
export class __Entity__Form extends BaseForm {
  private readonly formBuilder = inject(FormBuilder);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly store = inject(__Context__Store);

  protected readonly form = this.formBuilder.group({
    name: new FormControl<string>('', {nonNullable: true, validators: [Validators.required]})
  });

  protected readonly __entity__Id: number | null;
  protected readonly isEdit: boolean;

  constructor() {
    super();
    const id = this.route.snapshot.paramMap.get('id');
    this.__entity__Id = id ? Number(id) : null;
    this.isEdit = this.__entity__Id !== null;
    if (this.__entity__Id !== null) {
      const __entity__ = this.store.get__Entity__ById(this.__entity__Id)();
      if (__entity__) this.form.patchValue({name: __entity__.name});
    }
  }

  /**
   * Builds the __entity__ from the form and sends it through the store.
   */
  protected submit(): void {
    if (this.form.invalid) return;
    const __entity__ = new __Entity__({
      id: this.__entity__Id ?? 0,
      name: this.form.value.name!
    });
    if (this.isEdit) this.store.update__Entity__(__entity__);
    else this.store.add__Entity__(__entity__);
    this.router.navigate(['__context__/__entities-kebab__']).then();
  }
}

// skills/ddd-vue/assets/context-template/__context__/presentation/views/__entity-kebab__-form.vue
<script setup>
/**
 * @component __Entity__Form
 * @description Routed view that creates or edits one __entity__.
 *
 * One view serves both routes -- the presence of an `id` parameter decides which.
 * It collects input, builds a {@link __Entity__}, and hands it to the store. The
 * backend validates again and stays the authority.
 */
import {computed, onMounted, reactive} from 'vue';
import {useRoute, useRouter} from 'vue-router';
import use__Context__Store from '../../application/__context__.store.js';
import {__Entity__} from '../../domain/model/__entity-kebab__.entity.js';

const route = useRoute();
const router = useRouter();
const store = use__Context__Store();
const {add__Entity__, update__Entity__} = store;

const form = reactive({name: ''});
const isEdit = computed(() => !!route.params.id);

onMounted(() => {
  if (!isEdit.value) return;
  const __entity__ = store.get__Entity__ById(route.params.id);
  if (__entity__) form.name = __entity__.name;
  else navigateBack();
});

/**
 * Builds the __entity__ from the form and sends it through the store.
 * @returns {void}
 */
function save__Entity__() {
  const __entity__ = new __Entity__({
    id: isEdit.value ? Number(route.params.id) : null,
    name: form.name
  });
  if (isEdit.value) update__Entity__(__entity__);
  else add__Entity__(__entity__);
  navigateBack();
}

/**
 * Returns to the list.
 * @returns {void}
 */
function navigateBack() {
  router.push({name: '__context__-__entities-kebab__'});
}
</script>

<template>
  <section>
    <h1>{{ isEdit ? 'Edit __Entity__' : 'New __Entity__' }}</h1>

    <form @submit.prevent="save__Entity__">
      <label for="name">Name</label>
      <input id="name" v-model="form.name" required type="text"/>

      <button type="submit">{{ isEdit ? 'Update' : 'Create' }}</button>
      <button type="button" @click="navigateBack">Cancel</button>
    </form>
  </section>
</template>
