// skills/ddd-angular/assets/context-template/__context__/presentation/views/__entity-kebab__-list/__entity-kebab__-list.ts
import {Component, inject} from '@angular/core';
import {Router} from '@angular/router';
import {__Context__Store} from '../../../application/__context__.store';

/**
 * Routed view listing the __entities__ of the __context__ context.
 *
 * @remarks
 * A view is the smart component — it injects the store, reads its signals and
 * dispatches user intent. It holds no business logic and no HTTP call.
 */
@Component({
  selector: 'app-__entity-kebab__-list',
  templateUrl: './__entity-kebab__-list.html',
  styleUrl: './__entity-kebab__-list.css'
})
export class __Entity__List {
  protected readonly store = inject(__Context__Store);
  private readonly router = inject(Router);

  /**
   * @param id - Identity of the __entity__ to edit.
   */
  protected edit__Entity__(id: number): void {
    this.router.navigate(['__context__/__entities-kebab__', id, 'edit']).then();
  }

  /**
   * @param id - Identity of the __entity__ to delete.
   */
  protected delete__Entity__(id: number): void {
    this.store.delete__Entity__(id);
  }

  protected navigateToNew(): void {
    this.router.navigate(['__context__/__entities-kebab__/new']).then();
  }
}

// skills/ddd-vue/assets/context-template/__context__/presentation/views/__entity-kebab__-list.vue
<script setup>
/**
 * @component __Entity__List
 * @description Routed view listing the __entities__ of the __context__ context.
 *
 * A view is the smart component: it reads store state, dispatches actions and
 * navigates. It holds no business rule and makes no HTTP call.
 */
import {onMounted} from 'vue';
import {storeToRefs} from 'pinia';
import {useRouter} from 'vue-router';
import use__Context__Store from '../../application/__context__.store.js';

const router = useRouter();
const store = use__Context__Store();
const {__entities__, errors, __entities__Loaded} = storeToRefs(store);
const {fetch__Entities__, delete__Entity__} = store;

onMounted(() => {
  if (!__entities__Loaded.value) fetch__Entities__();
});

/**
 * Navigates to the creation form.
 * @returns {void}
 */
function navigateToNew() {
  router.push({name: '__context__-__entity-kebab__-new'});
}

/**
 * Navigates to the edit form for one __entity__.
 * @param {number} id - Identity of the __entity__ to edit.
 * @returns {void}
 */
function navigateToEdit(id) {
  router.push({name: '__context__-__entity-kebab__-edit', params: {id}});
}
</script>

<template>
  <section>
    <h1>__Entities__</h1>

    <p v-if="!__entities__Loaded">Loading…</p>
    <p v-if="errors.length" role="alert">{{ errors.map(error => error.message).join(', ') }}</p>

    <ul>
      <li v-for="__entity__ in __entities__" :key="__entity__.id">
        <span>{{ __entity__.name }}</span>
        <button type="button" @click="navigateToEdit(__entity__.id)">Edit</button>
        <button type="button" @click="delete__Entity__(__entity__)">Delete</button>
      </li>
    </ul>

    <button type="button" @click="navigateToNew">New __Entity__</button>
  </section>
</template>
